import 'package:easy_localization/easy_localization.dart';
import 'package:more_useful_clash_of_clans/utils/constants/locale_key.dart';
import 'package:nb_utils/nb_utils.dart';

import '../../models/api/response/location_response_model.dart';

class LocationHelper {
  static final locations = <LocationItem>[
    //LocationItem(id: 32000000, name: 'Europe', isCountry: false),
    //LocationItem(id: 32000001, name: 'North America', isCountry: false),
    //LocationItem(id: 32000002, name: 'South America', isCountry: false),
    //LocationItem(id: 32000003, name: 'Asia', isCountry: false),
    //LocationItem(id: 32000004, name: 'Australia', isCountry: false),
    //LocationItem(id: 32000005, name: 'Africa', isCountry: false),
    LocationItem(id: 32000006, name: 'International', isCountry: false),
    LocationItem(id: 32000007, name: 'Afghanistan', isCountry: true, countryCode: 'AF'),
    LocationItem(id: 32000008, name: 'Åland Islands', isCountry: true, countryCode: 'AX'),
    LocationItem(id: 32000009, name: 'Albania', isCountry: true, countryCode: 'AL'),
    LocationItem(id: 32000010, name: 'Algeria', isCountry: true, countryCode: 'DZ'),
    LocationItem(id: 32000011, name: 'American Samoa', isCountry: true, countryCode: 'AS'),
    LocationItem(id: 32000012, name: 'Andorra', isCountry: true, countryCode: 'AD'),
    LocationItem(id: 32000013, name: 'Angola', isCountry: true, countryCode: 'AO'),
    LocationItem(id: 32000014, name: 'Anguilla', isCountry: true, countryCode: 'AI'),
    LocationItem(id: 32000015, name: 'Antarctica', isCountry: true, countryCode: 'AQ'),
    LocationItem(id: 32000016, name: 'Antigua and Barbuda', isCountry: true, countryCode: 'AG'),
    LocationItem(id: 32000017, name: 'Argentina', isCountry: true, countryCode: 'AR'),
    LocationItem(id: 32000018, name: 'Armenia', isCountry: true, countryCode: 'AM'),
    LocationItem(id: 32000019, name: 'Aruba', isCountry: true, countryCode: 'AW'),
    LocationItem(id: 32000020, name: 'Ascension Island', isCountry: true, countryCode: 'AC'),
    LocationItem(id: 32000021, name: 'Australia', isCountry: true, countryCode: 'AU'),
    LocationItem(id: 32000022, name: 'Austria', isCountry: true, countryCode: 'AT'),
    LocationItem(id: 32000023, name: 'Azerbaijan', isCountry: true, countryCode: 'AZ'),
    LocationItem(id: 32000024, name: 'Bahamas', isCountry: true, countryCode: 'BS'),
    LocationItem(id: 32000025, name: 'Bahrain', isCountry: true, countryCode: 'BH'),
    LocationItem(id: 32000026, name: 'Bangladesh', isCountry: true, countryCode: 'BD'),
    LocationItem(id: 32000027, name: 'Barbados', isCountry: true, countryCode: 'BB'),
    LocationItem(id: 32000028, name: 'Belarus', isCountry: true, countryCode: 'BY'),
    LocationItem(id: 32000029, name: 'Belgium', isCountry: true, countryCode: 'BE'),
    LocationItem(id: 32000030, name: 'Belize', isCountry: true, countryCode: 'BZ'),
    LocationItem(id: 32000031, name: 'Benin', isCountry: true, countryCode: 'BJ'),
    LocationItem(id: 32000032, name: 'Bermuda', isCountry: true, countryCode: 'BM'),
    LocationItem(id: 32000033, name: 'Bhutan', isCountry: true, countryCode: 'BT'),
    LocationItem(id: 32000034, name: 'Bolivia', isCountry: true, countryCode: 'BO'),
    LocationItem(id: 32000035, name: 'Bosnia and Herzegovina', isCountry: true, countryCode: 'BA'),
    LocationItem(id: 32000036, name: 'Botswana', isCountry: true, countryCode: 'BW'),
    LocationItem(id: 32000037, name: 'Bouvet Island', isCountry: true, countryCode: 'BV'),
    LocationItem(id: 32000038, name: 'Brazil', isCountry: true, countryCode: 'BR'),
    LocationItem(id: 32000039, name: 'British Indian Ocean Territory', isCountry: true, countryCode: 'IO'),
    LocationItem(id: 32000040, name: 'British Virgin Islands', isCountry: true, countryCode: 'VG'),
    LocationItem(id: 32000041, name: 'Brunei', isCountry: true, countryCode: 'BN'),
    LocationItem(id: 32000042, name: 'Bulgaria', isCountry: true, countryCode: 'BG'),
    LocationItem(id: 32000043, name: 'Burkina Faso', isCountry: true, countryCode: 'BF'),
    LocationItem(id: 32000044, name: 'Burundi', isCountry: true, countryCode: 'BI'),
    LocationItem(id: 32000045, name: 'Cambodia', isCountry: true, countryCode: 'KH'),
    LocationItem(id: 32000046, name: 'Cameroon', isCountry: true, countryCode: 'CM'),
    LocationItem(id: 32000047, name: 'Canada', isCountry: true, countryCode: 'CA'),
    LocationItem(id: 32000048, name: 'Canary Islands', isCountry: true, countryCode: 'IC'),
    LocationItem(id: 32000049, name: 'Cape Verde', isCountry: true, countryCode: 'CV'),
    LocationItem(id: 32000050, name: 'Caribbean Netherlands', isCountry: true, countryCode: 'BQ'),
    LocationItem(id: 32000051, name: 'Cayman Islands', isCountry: true, countryCode: 'KY'),
    LocationItem(id: 32000052, name: 'Central African Republic', isCountry: true, countryCode: 'CF'),
    LocationItem(id: 32000053, name: 'Ceuta and Melilla', isCountry: true, countryCode: 'EA'),
    LocationItem(id: 32000054, name: 'Chad', isCountry: true, countryCode: 'TD'),
    LocationItem(id: 32000055, name: 'Chile', isCountry: true, countryCode: 'CL'),
    LocationItem(id: 32000056, name: 'China', isCountry: true, countryCode: 'CN'),
    LocationItem(id: 32000057, name: 'Christmas Island', isCountry: true, countryCode: 'CX'),
    LocationItem(id: 32000058, name: 'Cocos (Keeling) Islands', isCountry: true, countryCode: 'CC'),
    LocationItem(id: 32000059, name: 'Colombia', isCountry: true, countryCode: 'CO'),
    LocationItem(id: 32000060, name: 'Comoros', isCountry: true, countryCode: 'KM'),
    LocationItem(id: 32000061, name: 'Congo (DRC)', isCountry: true, countryCode: 'CG'),
    LocationItem(id: 32000062, name: 'Congo (Republic)', isCountry: true, countryCode: 'CD'),
    LocationItem(id: 32000063, name: 'Cook Islands', isCountry: true, countryCode: 'CK'),
    LocationItem(id: 32000064, name: 'Costa Rica', isCountry: true, countryCode: 'CR'),
    LocationItem(id: 32000065, name: 'Côte d’Ivoire', isCountry: true, countryCode: 'CI'),
    LocationItem(id: 32000066, name: 'Croatia', isCountry: true, countryCode: 'HR'),
    LocationItem(id: 32000067, name: 'Cuba', isCountry: true, countryCode: 'CU'),
    LocationItem(id: 32000068, name: 'Curaçao', isCountry: true, countryCode: 'CW'),
    LocationItem(id: 32000069, name: 'Cyprus', isCountry: true, countryCode: 'CY'),
    LocationItem(id: 32000070, name: 'Czech Republic', isCountry: true, countryCode: 'CZ'),
    LocationItem(id: 32000071, name: 'Denmark', isCountry: true, countryCode: 'DK'),
    LocationItem(id: 32000072, name: 'Diego Garcia', isCountry: true, countryCode: 'DG'),
    LocationItem(id: 32000073, name: 'Djibouti', isCountry: true, countryCode: 'DJ'),
    LocationItem(id: 32000074, name: 'Dominica', isCountry: true, countryCode: 'DM'),
    LocationItem(id: 32000075, name: 'Dominican Republic', isCountry: true, countryCode: 'DO'),
    LocationItem(id: 32000076, name: 'Ecuador', isCountry: true, countryCode: 'EC'),
    LocationItem(id: 32000077, name: 'Egypt', isCountry: true, countryCode: 'EG'),
    LocationItem(id: 32000078, name: 'El Salvador', isCountry: true, countryCode: 'SV'),
    LocationItem(id: 32000079, name: 'Equatorial Guinea', isCountry: true, countryCode: 'GQ'),
    LocationItem(id: 32000080, name: 'Eritrea', isCountry: true, countryCode: 'ER'),
    LocationItem(id: 32000081, name: 'Estonia', isCountry: true, countryCode: 'EE'),
    LocationItem(id: 32000082, name: 'Ethiopia', isCountry: true, countryCode: 'ET'),
    LocationItem(id: 32000083, name: 'Falkland Islands', isCountry: true, countryCode: 'FK'),
    LocationItem(id: 32000084, name: 'Faroe Islands', isCountry: true, countryCode: 'FO'),
    LocationItem(id: 32000085, name: 'Fiji', isCountry: true, countryCode: 'FJ'),
    LocationItem(id: 32000086, name: 'Finland', isCountry: true, countryCode: 'FI'),
    LocationItem(id: 32000087, name: 'France', isCountry: true, countryCode: 'FR'),
    LocationItem(id: 32000088, name: 'French Guiana', isCountry: true, countryCode: 'GF'),
    LocationItem(id: 32000089, name: 'French Polynesia', isCountry: true, countryCode: 'PF'),
    LocationItem(id: 32000090, name: 'French Southern Territories', isCountry: true, countryCode: 'TF'),
    LocationItem(id: 32000091, name: 'Gabon', isCountry: true, countryCode: 'GA'),
    LocationItem(id: 32000092, name: 'Gambia', isCountry: true, countryCode: 'GM'),
    LocationItem(id: 32000093, name: 'Georgia', isCountry: true, countryCode: 'GE'),
    LocationItem(id: 32000094, name: 'Germany', isCountry: true, countryCode: 'DE'),
    LocationItem(id: 32000095, name: 'Ghana', isCountry: true, countryCode: 'GH'),
    LocationItem(id: 32000096, name: 'Gibraltar', isCountry: true, countryCode: 'GI'),
    LocationItem(id: 32000097, name: 'Greece', isCountry: true, countryCode: 'GR'),
    LocationItem(id: 32000098, name: 'Greenland', isCountry: true, countryCode: 'GL'),
    LocationItem(id: 32000099, name: 'Grenada', isCountry: true, countryCode: 'GD'),
    LocationItem(id: 32000100, name: 'Guadeloupe', isCountry: true, countryCode: 'GP'),
    LocationItem(id: 32000101, name: 'Guam', isCountry: true, countryCode: 'GU'),
    LocationItem(id: 32000102, name: 'Guatemala', isCountry: true, countryCode: 'GT'),
    LocationItem(id: 32000103, name: 'Guernsey', isCountry: true, countryCode: 'GG'),
    LocationItem(id: 32000104, name: 'Guinea', isCountry: true, countryCode: 'GN'),
    LocationItem(id: 32000105, name: 'Guinea-Bissau', isCountry: true, countryCode: 'GW'),
    LocationItem(id: 32000106, name: 'Guyana', isCountry: true, countryCode: 'GY'),
    LocationItem(id: 32000107, name: 'Haiti', isCountry: true, countryCode: 'HT'),
    LocationItem(id: 32000108, name: 'Heard & McDonald Islands', isCountry: true, countryCode: 'HM'),
    LocationItem(id: 32000109, name: 'Honduras', isCountry: true, countryCode: 'HN'),
    LocationItem(id: 32000110, name: 'Hong Kong', isCountry: true, countryCode: 'HK'),
    LocationItem(id: 32000111, name: 'Hungary', isCountry: true, countryCode: 'HU'),
    LocationItem(id: 32000112, name: 'Iceland', isCountry: true, countryCode: 'IS'),
    LocationItem(id: 32000113, name: 'India', isCountry: true, countryCode: 'IN'),
    LocationItem(id: 32000114, name: 'Indonesia', isCountry: true, countryCode: 'ID'),
    LocationItem(id: 32000115, name: 'Iran', isCountry: true, countryCode: 'IR'),
    LocationItem(id: 32000116, name: 'Iraq', isCountry: true, countryCode: 'IQ'),
    LocationItem(id: 32000117, name: 'Ireland', isCountry: true, countryCode: 'IE'),
    LocationItem(id: 32000118, name: 'Isle of Man', isCountry: true, countryCode: 'IM'),
    LocationItem(id: 32000119, name: 'Israel', isCountry: true, countryCode: 'IL'),
    LocationItem(id: 32000120, name: 'Italy', isCountry: true, countryCode: 'IT'),
    LocationItem(id: 32000121, name: 'Jamaica', isCountry: true, countryCode: 'JM'),
    LocationItem(id: 32000122, name: 'Japan', isCountry: true, countryCode: 'JP'),
    LocationItem(id: 32000123, name: 'Jersey', isCountry: true, countryCode: 'JE'),
    LocationItem(id: 32000124, name: 'Jordan', isCountry: true, countryCode: 'JO'),
    LocationItem(id: 32000125, name: 'Kazakhstan', isCountry: true, countryCode: 'KZ'),
    LocationItem(id: 32000126, name: 'Kenya', isCountry: true, countryCode: 'KE'),
    LocationItem(id: 32000127, name: 'Kiribati', isCountry: true, countryCode: 'KI'),
    LocationItem(id: 32000128, name: 'Kosovo', isCountry: true, countryCode: 'XK'),
    LocationItem(id: 32000129, name: 'Kuwait', isCountry: true, countryCode: 'KW'),
    LocationItem(id: 32000130, name: 'Kyrgyzstan', isCountry: true, countryCode: 'KG'),
    LocationItem(id: 32000131, name: 'Laos', isCountry: true, countryCode: 'LA'),
    LocationItem(id: 32000132, name: 'Latvia', isCountry: true, countryCode: 'LV'),
    LocationItem(id: 32000133, name: 'Lebanon', isCountry: true, countryCode: 'LB'),
    LocationItem(id: 32000134, name: 'Lesotho', isCountry: true, countryCode: 'LS'),
    LocationItem(id: 32000135, name: 'Liberia', isCountry: true, countryCode: 'LR'),
    LocationItem(id: 32000136, name: 'Libya', isCountry: true, countryCode: 'LY'),
    LocationItem(id: 32000137, name: 'Liechtenstein', isCountry: true, countryCode: 'LI'),
    LocationItem(id: 32000138, name: 'Lithuania', isCountry: true, countryCode: 'LT'),
    LocationItem(id: 32000139, name: 'Luxembourg', isCountry: true, countryCode: 'LU'),
    LocationItem(id: 32000140, name: 'Macau', isCountry: true, countryCode: 'MO'),
    LocationItem(id: 32000141, name: 'North Macedonia', isCountry: true, countryCode: 'MK'),
    LocationItem(id: 32000142, name: 'Madagascar', isCountry: true, countryCode: 'MG'),
    LocationItem(id: 32000143, name: 'Malawi', isCountry: true, countryCode: 'MW'),
    LocationItem(id: 32000144, name: 'Malaysia', isCountry: true, countryCode: 'MY'),
    LocationItem(id: 32000145, name: 'Maldives', isCountry: true, countryCode: 'MV'),
    LocationItem(id: 32000146, name: 'Mali', isCountry: true, countryCode: 'ML'),
    LocationItem(id: 32000147, name: 'Malta', isCountry: true, countryCode: 'MT'),
    LocationItem(id: 32000148, name: 'Marshall Islands', isCountry: true, countryCode: 'MH'),
    LocationItem(id: 32000149, name: 'Martinique', isCountry: true, countryCode: 'MQ'),
    LocationItem(id: 32000150, name: 'Mauritania', isCountry: true, countryCode: 'MR'),
    LocationItem(id: 32000151, name: 'Mauritius', isCountry: true, countryCode: 'MU'),
    LocationItem(id: 32000152, name: 'Mayotte', isCountry: true, countryCode: 'YT'),
    LocationItem(id: 32000153, name: 'Mexico', isCountry: true, countryCode: 'MX'),
    LocationItem(id: 32000154, name: 'Micronesia', isCountry: true, countryCode: 'FM'),
    LocationItem(id: 32000155, name: 'Moldova', isCountry: true, countryCode: 'MD'),
    LocationItem(id: 32000156, name: 'Monaco', isCountry: true, countryCode: 'MC'),
    LocationItem(id: 32000157, name: 'Mongolia', isCountry: true, countryCode: 'MN'),
    LocationItem(id: 32000158, name: 'Montenegro', isCountry: true, countryCode: 'ME'),
    LocationItem(id: 32000159, name: 'Montserrat', isCountry: true, countryCode: 'MS'),
    LocationItem(id: 32000160, name: 'Morocco', isCountry: true, countryCode: 'MA'),
    LocationItem(id: 32000161, name: 'Mozambique', isCountry: true, countryCode: 'MZ'),
    LocationItem(id: 32000162, name: 'Myanmar (Burma)', isCountry: true, countryCode: 'MM'),
    LocationItem(id: 32000163, name: 'Namibia', isCountry: true, countryCode: 'NA'),
    LocationItem(id: 32000164, name: 'Nauru', isCountry: true, countryCode: 'NR'),
    LocationItem(id: 32000165, name: 'Nepal', isCountry: true, countryCode: 'NP'),
    LocationItem(id: 32000166, name: 'Netherlands', isCountry: true, countryCode: 'NL'),
    LocationItem(id: 32000167, name: 'New Caledonia', isCountry: true, countryCode: 'NC'),
    LocationItem(id: 32000168, name: 'New Zealand', isCountry: true, countryCode: 'NZ'),
    LocationItem(id: 32000169, name: 'Nicaragua', isCountry: true, countryCode: 'NI'),
    LocationItem(id: 32000170, name: 'Niger', isCountry: true, countryCode: 'NE'),
    LocationItem(id: 32000171, name: 'Nigeria', isCountry: true, countryCode: 'NG'),
    LocationItem(id: 32000172, name: 'Niue', isCountry: true, countryCode: 'NU'),
    LocationItem(id: 32000173, name: 'Norfolk Island', isCountry: true, countryCode: 'NF'),
    LocationItem(id: 32000174, name: 'North Korea', isCountry: true, countryCode: 'KP'),
    LocationItem(id: 32000175, name: 'Northern Mariana Islands', isCountry: true, countryCode: 'MP'),
    LocationItem(id: 32000176, name: 'Norway', isCountry: true, countryCode: 'NO'),
    LocationItem(id: 32000177, name: 'Oman', isCountry: true, countryCode: 'OM'),
    LocationItem(id: 32000178, name: 'Pakistan', isCountry: true, countryCode: 'PK'),
    LocationItem(id: 32000179, name: 'Palau', isCountry: true, countryCode: 'PW'),
    LocationItem(id: 32000180, name: 'Palestine', isCountry: true, countryCode: 'PS'),
    LocationItem(id: 32000181, name: 'Panama', isCountry: true, countryCode: 'PA'),
    LocationItem(id: 32000182, name: 'Papua New Guinea', isCountry: true, countryCode: 'PG'),
    LocationItem(id: 32000183, name: 'Paraguay', isCountry: true, countryCode: 'PY'),
    LocationItem(id: 32000184, name: 'Peru', isCountry: true, countryCode: 'PE'),
    LocationItem(id: 32000185, name: 'Philippines', isCountry: true, countryCode: 'PH'),
    LocationItem(id: 32000186, name: 'Pitcairn Islands', isCountry: true, countryCode: 'PN'),
    LocationItem(id: 32000187, name: 'Poland', isCountry: true, countryCode: 'PL'),
    LocationItem(id: 32000188, name: 'Portugal', isCountry: true, countryCode: 'PT'),
    LocationItem(id: 32000189, name: 'Puerto Rico', isCountry: true, countryCode: 'PR'),
    LocationItem(id: 32000190, name: 'Qatar', isCountry: true, countryCode: 'QA'),
    LocationItem(id: 32000191, name: 'Réunion', isCountry: true, countryCode: 'RE'),
    LocationItem(id: 32000192, name: 'Romania', isCountry: true, countryCode: 'RO'),
    LocationItem(id: 32000193, name: 'Russia', isCountry: true, countryCode: 'RU'),
    LocationItem(id: 32000194, name: 'Rwanda', isCountry: true, countryCode: 'RW'),
    LocationItem(id: 32000195, name: 'Saint Barthélemy', isCountry: true, countryCode: 'BL'),
    LocationItem(id: 32000196, name: 'Saint Helena', isCountry: true, countryCode: 'SH'),
    LocationItem(id: 32000197, name: 'Saint Kitts and Nevis', isCountry: true, countryCode: 'KN'),
    LocationItem(id: 32000198, name: 'Saint Lucia', isCountry: true, countryCode: 'LC'),
    LocationItem(id: 32000199, name: 'Saint Martin', isCountry: true, countryCode: 'MF'),
    LocationItem(id: 32000200, name: 'Saint Pierre and Miquelon', isCountry: true, countryCode: 'PM'),
    LocationItem(id: 32000201, name: 'Samoa', isCountry: true, countryCode: 'WS'),
    LocationItem(id: 32000202, name: 'San Marino', isCountry: true, countryCode: 'SM'),
    LocationItem(id: 32000203, name: 'São Tomé and Príncipe', isCountry: true, countryCode: 'ST'),
    LocationItem(id: 32000204, name: 'Saudi Arabia', isCountry: true, countryCode: 'SA'),
    LocationItem(id: 32000205, name: 'Senegal', isCountry: true, countryCode: 'SN'),
    LocationItem(id: 32000206, name: 'Serbia', isCountry: true, countryCode: 'RS'),
    LocationItem(id: 32000207, name: 'Seychelles', isCountry: true, countryCode: 'SC'),
    LocationItem(id: 32000208, name: 'Sierra Leone', isCountry: true, countryCode: 'SL'),
    LocationItem(id: 32000209, name: 'Singapore', isCountry: true, countryCode: 'SG'),
    LocationItem(id: 32000210, name: 'Sint Maarten', isCountry: true, countryCode: 'SX'),
    LocationItem(id: 32000211, name: 'Slovakia', isCountry: true, countryCode: 'SK'),
    LocationItem(id: 32000212, name: 'Slovenia', isCountry: true, countryCode: 'SI'),
    LocationItem(id: 32000213, name: 'Solomon Islands', isCountry: true, countryCode: 'SB'),
    LocationItem(id: 32000214, name: 'Somalia', isCountry: true, countryCode: 'SO'),
    LocationItem(id: 32000215, name: 'South Africa', isCountry: true, countryCode: 'ZA'),
    LocationItem(id: 32000216, name: 'South Korea', isCountry: true, countryCode: 'KR'),
    LocationItem(id: 32000217, name: 'South Sudan', isCountry: true, countryCode: 'SS'),
    LocationItem(id: 32000218, name: 'Spain', isCountry: true, countryCode: 'ES'),
    LocationItem(id: 32000219, name: 'Sri Lanka', isCountry: true, countryCode: 'LK'),
    LocationItem(id: 32000220, name: 'St. Vincent & Grenadines', isCountry: true, countryCode: 'VC'),
    LocationItem(id: 32000221, name: 'Sudan', isCountry: true, countryCode: 'SD'),
    LocationItem(id: 32000222, name: 'Suriname', isCountry: true, countryCode: 'SR'),
    LocationItem(id: 32000223, name: 'Svalbard and Jan Mayen', isCountry: true, countryCode: 'SJ'),
    LocationItem(id: 32000224, name: 'Swaziland', isCountry: true, countryCode: 'SZ'),
    LocationItem(id: 32000225, name: 'Sweden', isCountry: true, countryCode: 'SE'),
    LocationItem(id: 32000226, name: 'Switzerland', isCountry: true, countryCode: 'CH'),
    LocationItem(id: 32000227, name: 'Syria', isCountry: true, countryCode: 'SY'),
    LocationItem(id: 32000228, name: 'Taiwan', isCountry: true, countryCode: 'TW'),
    LocationItem(id: 32000229, name: 'Tajikistan', isCountry: true, countryCode: 'TJ'),
    LocationItem(id: 32000230, name: 'Tanzania', isCountry: true, countryCode: 'TZ'),
    LocationItem(id: 32000231, name: 'Thailand', isCountry: true, countryCode: 'TH'),
    LocationItem(id: 32000232, name: 'Timor-Leste', isCountry: true, countryCode: 'TL'),
    LocationItem(id: 32000233, name: 'Togo', isCountry: true, countryCode: 'TG'),
    LocationItem(id: 32000234, name: 'Tokelau', isCountry: true, countryCode: 'TK'),
    LocationItem(id: 32000235, name: 'Tonga', isCountry: true, countryCode: 'TO'),
    LocationItem(id: 32000236, name: 'Trinidad and Tobago', isCountry: true, countryCode: 'TT'),
    LocationItem(id: 32000237, name: 'Tristan da Cunha', isCountry: true, countryCode: 'TA'),
    LocationItem(id: 32000238, name: 'Tunisia', isCountry: true, countryCode: 'TN'),
    LocationItem(id: 32000239, name: 'Türkiye', isCountry: true, countryCode: 'TR'),
    LocationItem(id: 32000240, name: 'Turkmenistan', isCountry: true, countryCode: 'TM'),
    LocationItem(id: 32000241, name: 'Turks and Caicos Islands', isCountry: true, countryCode: 'TC'),
    LocationItem(id: 32000242, name: 'Tuvalu', isCountry: true, countryCode: 'TV'),
    LocationItem(id: 32000243, name: 'U.S. Outlying Islands', isCountry: true, countryCode: 'UM'),
    LocationItem(id: 32000244, name: 'U.S. Virgin Islands', isCountry: true, countryCode: 'VI'),
    LocationItem(id: 32000245, name: 'Uganda', isCountry: true, countryCode: 'UG'),
    LocationItem(id: 32000246, name: 'Ukraine', isCountry: true, countryCode: 'UA'),
    LocationItem(id: 32000247, name: 'United Arab Emirates', isCountry: true, countryCode: 'AE'),
    LocationItem(id: 32000248, name: 'United Kingdom', isCountry: true, countryCode: 'GB'),
    LocationItem(id: 32000249, name: 'United States', isCountry: true, countryCode: 'US'),
    LocationItem(id: 32000250, name: 'Uruguay', isCountry: true, countryCode: 'UY'),
    LocationItem(id: 32000251, name: 'Uzbekistan', isCountry: true, countryCode: 'UZ'),
    LocationItem(id: 32000252, name: 'Vanuatu', isCountry: true, countryCode: 'VU'),
    LocationItem(id: 32000253, name: 'Vatican City', isCountry: true, countryCode: 'VA'),
    LocationItem(id: 32000254, name: 'Venezuela', isCountry: true, countryCode: 'VE'),
    LocationItem(id: 32000255, name: 'Vietnam', isCountry: true, countryCode: 'VN'),
    LocationItem(id: 32000256, name: 'Wallis and Futuna', isCountry: true, countryCode: 'WF'),
    LocationItem(id: 32000257, name: 'Western Sahara', isCountry: true, countryCode: 'EH'),
    LocationItem(id: 32000258, name: 'Yemen', isCountry: true, countryCode: 'YE'),
    LocationItem(id: 32000259, name: 'Zambia', isCountry: true, countryCode: 'ZM'),
    LocationItem(id: 32000260, name: 'Zimbabwe', isCountry: true, countryCode: 'ZW'),
    //LocationItem(id: 32000261, name: '', isCountry: false),
    //LocationItem(id: 32000262, name: '', isCountry: false),
    //LocationItem(id: 32000263, name: '', isCountry: false),
    //LocationItem(id: 32000264, name: '', isCountry: false),
    //LocationItem(id: 32000265, name: '', isCountry: false),
  ];

  static List<LocationItem> getAll(bool addAny) {
    final list = locations.where((l) => !l.name.isEmptyOrNull).toList();
    if (addAny) {
      list.insert(
          0, LocationItem(id: -1, name: tr(LocaleKey.any), isCountry: false));
    }
    return list;
  }
}
